spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.168.153:3306/myblog?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: enjoyIT123


mybatis:
  type-aliases-package: com.wdd.myblog.entity
  mapper-locations: classpath:mapper/*.xml

var:
  filePath: \\src\\main\\resources\\static\\upload\\
